# Generated by Django 2.0.3 on 2018-06-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0002_auto_20180628_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='address',
            name='flat_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='email',
            name='e_mail',
            field=models.EmailField(default=None, max_length=64),
        ),
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.CharField(default=None, max_length=32),
        ),
        migrations.AlterField(
            model_name='phone',
            name='number',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(default=None, max_length=32),
        ),
    ]
