# Generated by Django 2.0.3 on 2018-06-29 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0004_auto_20180629_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='brak', max_length=64),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(default='brak', max_length=64),
        ),
        migrations.AlterField(
            model_name='email',
            name='type',
            field=models.CharField(default='brak', max_length=32),
        ),
        migrations.AlterField(
            model_name='phone',
            name='type',
            field=models.CharField(default='brak', max_length=32),
        ),
    ]
