# Generated by Django 2.0.3 on 2018-06-29 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address_book', '0005_auto_20180629_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='name',
            field=models.CharField(default='brak', max_length=128),
        ),
    ]
